### ISSUE TITLE
PIP or PIP3?

### ISSUE THREAD

**Issue by ArjenR49** [frtz13/UPSPlus_mqtt#1]
Your package looks great. I'm going to install it today instead of (or next to) what I cobbled together from the GeeekPi scripts based on my own preferences and driven by the persistent problems I have experienced with the i2c bus of the UPS.
I have never learned any OOP, or what is it called today, and it has always felt very complicated. At last I have what looks like a proper example to learn from. Thanks! Even FAN control of a two wire FAN (Ice Tower). Time to get the soldering iron out and find that MOSFET.

I have a question: shouldn't pip be pip3 nowadays?

**Comment by frtz13** [comment]
you are right about pip3.
if you don't have a corresponding MOSFET in your junk box, a simple NPN transistor (2N2222, BC137 or whatever) and a 680 Ohm resistor from GPIO pin to the base do the job here.
