### ISSUE TITLE
HA not get UPS Battery

### ISSUE THREAD

**Issue by hellresistor** [frtz13/UPSPlus_mqtt#11]
The image has much value than words ;)
![haa](https://user-images.githubusercontent.com/50468493/120938225-a9108f80-c709-11eb-9789-34373a5ac0af.jpg)

**Comment by frtz13** [comment]
I guess there is a problem with the binary sensor definition. Did you check with the binary sensor definition in HA_config_ups_fan.yaml ? Did you check if this binary sensor is visible and "available" in Home Assistant / Developer Tools / States ?

**Comment by hellresistor** [comment]
You are right|
Now I am using your .yaml content.
I was used my old-text. o/
