### ISSUE TITLE
maybe code problem? if not. close issue.

### ISSUE THREAD

**Issue by hellresistor** [frtz13/UPSPlus_mqtt#16]
hello.

I have running your scrypt and detect i am getting 65% (but have 4.2V).
check here: https://github.com/geeekpi/upsplus/issues/69

fanshutdown.ini:
```
[ups]
SEND_STATUS_TO_UPSPLUS_IOT_PLATFORM = 1
UPSPLUS_IOT_PLATFORM_URL = https://api.52pi.com/feed
BATTERY_CHECK_LOOP_TIME_s = 60
SHUTDOWN_TIMEOUT_s = 120
PROTECTION_VOLTAGE_MARGIN_mV = 300
```

PS: I will try with yours new update.
PS2: Same with repository update

**Comment by frtz13** [comment]
the script does not have any influence on charging characteristics.
