### ISSUE TITLE
ranges to be read over the i2c bus in hexadecimal

### ISSUE THREAD

**Issue by ArjenR49** [frtz13/UPSPlus_mqtt#21]
Thanks again for the new script version!

I prefer to write memory addresses in hexadecimal esp. because the table in the documentation is in hexadecimal.
```
        if SEND_STATUS_TO_UPSPLUS_IOT_PLATFORM:
#            it_registers = it.chain(range(1,42), range(240,252))
            it_registers = it.chain(range(0x01,0x2A), range(0xF0,0xFC))
        else:
#            it_registers = it.chain(range(7,12), range(0x11, 0x13), range(19,21))
            it_registers = it.chain(range(0x07,0x0C), range(0x11,0x13), range(0x13,0x15))

```
At first I thought there's an error because of overlapping ranges, but found out that ranges are defined such that the last address is not included ... and 0x0C also is not needed as you have stated in the comments before ...

**Comment by frtz13** [comment]
you are right. re-wrote all register addresses in hex.
