### ISSUE TITLE
Multiple identical processes: python3 /home/pi/UPSPlus_MQTT/fanShutDownUps.py

### ISSUE THREAD

**Issue by ArjenR49** [frtz13/UPSPlus_mqtt#22]
The script is started by launcher.sh in crontab as given in this Github project.

When I run htop, there are three exactly identical processes python3 /home/pi/UPSPlus_MQTT/fanShutDownUps.py  all owned by pi, viz. 407, 650 and 4217 in this case:
![Schermafdruk van 2021-09-06 08-22-39](https://user-images.githubusercontent.com/54793526/132170591-4f3a22a6-d514-4c4b-b5f8-139e19440999.png)
It strikes me as odd. Is it normal?

**Comment by frtz13** [comment]
I think so. same here. tree-view (F5) shows one process with 2 dependent processes. one of these is the MQTT loop as it is created after the MQTT connection is established.
