### ISSUE TITLE
question: protectionV_default_mV = 3700?

### ISSUE THREAD

**Issue by ArjenR49** [frtz13/UPSPlus_mqtt#4]
Is there a reason for this high value other than that it is what GeeekPi uses as a default?

Your script balks if there's another value in UPS memory.
3,7 V is very conservative. For my cells at full rated discharge the voltage is given as 2500 mV.
Of course, how deep you want to go depends on what you want from the UPS.

If one wants to go lower, one can set the chosen value both in memory and in the script and that would be that.
So, maybe the check is meant to be a safety check rather than a policy.

**Comment by frtz13** [comment]
currently, the script checks if the "protection voltage" read from the UPS registers is between 3000 and 4000 mV and keeps this value. if the value is outside these bounds, it assumes the value of 3700 mV.
I'll set the lower bound check to 2500 mV.
